#!/bin/bash

echo "setting configuration"

cat > /var/lib/postgresql/data/pg_hba.conf <<EOS
# Generated by fix-acl.sh
# TYPE  DATABASE        USER            ADDRESS                 METHOD
# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust

# Allow anyone to connect remotely so long as they have a valid username and
# password.
host all all 0.0.0.0/0 md5
hostssl all all 0.0.0.0/0 md5

host replication postgres 0.0.0.0/0 md5
EOS

# setting maximum concurrent connections to 1000
sed -i "s/max_connections = .*/max_connections = 1000/g" /var/lib/postgresql/data/postgresql.conf

# setting pg_stat_statements
sed -i "s/#shared_preload_libraries = .*/shared_preload_libraries = 'pg_stat_statements'/g" /var/lib/postgresql/data/postgresql.conf

echo "listen_addresses='*'
wal_level=hot_standby
max_wal_senders=3
wal_keep_segments=32
hot_standby=on

##  These are for profiling
# logging_collector = on
# log_min_duration_statement = 0
# log_destination = 'csvlog'
# log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
# log_checkpoints = on
# log_connections = on
# log_disconnections = on
# log_lock_waits = on
# log_temp_files = 0
# log_autovacuum_min_duration = 0
# log_directory = '/project/data/pgdata/'
# log_filename = 'postgresql-%Y-%m-%d_%H%M.log'

# synchronous_standby_names='*'
ssl = on
ssl_cert_file = '/ssl/server.crt'
ssl_key_file = '/ssl/server.key'
" >> /var/lib/postgresql/data/postgresql.conf
