version: "3.4"
services:
  databasesvc:
    image: gcr.io/alpacahq/gbi.postgresql
    build:
      context: compose/postgres
      dockerfile: Dockerfile
    env_file:
      - compose/env.core
      - compose/env.postgres
    ports:
      - 5432:5432
    user: 'postgres'
    volumes:
      - ./compose/postgres/db-scripts:/docker-entrypoint-initdb.d
      - ./compose/postgres/pgdata:/var/lib/postgresql/data
      - ./integration:/project

  pgmng:
    image: sosedoff/pgweb
    depends_on:
      - databasesvc  
    env_file:
      - compose/env.pgweb
    ports:
      - 8081:8081

  flagentsvc:
    image: gcr.io/alpacahq/flagent
    build:
      context: compose/flagent
      dockerfile: Dockerfile
    volumes:
      - ./compose/logs/fluentd:/var/log/fluentd
    command: run
      
  rmqsvc:
    image: rabbitmq:3.7.4-management-alpine
    volumes:
      - ./compose/rmqdata:/var/lib/rabbitmq/mnesia
    env_file:
      - compose/env.core
      - compose/env.rmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redissvc:
    image: redis:alpine3.8

  polycachesvc:
    image: alpacamarkets/polycache:v1.2.3
    volumes:
      - ./compose/prjcdata:/project
      - ./compose/cachedata:/data
    environment:
      TEST_MODE: "TRUE"
      RAFT_DIR: /data/poly
    env_file:
      - compose/env.core

  marketstoresvc:
    image: alpacamarkets/marketstore:v3.0.1
    volumes:
      - ./compose/mkts/data:/data
    env_file:
      - compose/env.core
    entrypoint:
      - 'marketstore'
      - 'start'
      - '-c'
      - '/data/mkts.yml'

  gtsetup:
    image: alpacamarkets/gotrader:v1.7.1
    depends_on: 
      - databasesvc
      - rmqsvc
    volumes:
      - ./compose/cachedata:/go/pkg
    environment:
      PGHOST: databasesvc
      SIMULATOR_DB: gotrader_sim
    entrypoint:
      - 'migrate'

  gotradersvc:
    image: alpacamarkets/gotrader:v1.7.1
    depends_on: 
      - databasesvc
      - rmqsvc
      - gtsetup
    volumes:
      - ./compose/prjdata:/project
    env_file:
      - compose/env.core
      - compose/env.gotrader
    restart: on-failure

  gbsetup:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - databasesvc
    volumes:
      - ./compose/cachedata:/go/pkg
    environment:
      PGHOST: databasesvc
    entrypoint:
      - migrate

  gobrokersvc:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - databasesvc
      - rmqsvc
      - polycachesvc
      - flagentsvc
      - gbsetup
    volumes:
      # - ./compose/prjdata:/project
      - .:/go/src/github.com/alpacahq/gobroker
      - ./integration:/project
    env_file:
      - compose/env.core
      - compose/env.gobroker

  gb-workerssvc:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - databasesvc
      - rmqsvc
      - gbsetup
    volumes:
      - ./compose/prjdata:/project
      - ./compose/cachedata:/go/pkg
    env_file:
      - compose/env.core
      - compose/env.gbworkers
    entrypoint: workers
  
  ptsetup:
    image: alpacamarkets/papertrader:v1.1.8
    depends_on: 
      - databasesvc
    volumes:
      - ./compose/cachedata:/go/pkg
    environment:
      PGHOST: databasesvc
    entrypoint:
      - migrate

  papertradersvc:
    image: alpacamarkets/papertrader:v1.1.8
    depends_on: 
      - databasesvc
      - rmqsvc
      - gbsetup
      - flagentsvc
    volumes:
      - ./compose/prjdata:/project
      - ./compose/cachedata:/go/pkg
    env_file:
      - compose/env.core
      - compose/env.papertrader

  nginxsvc:
    image: gcr.io/alpacahq/nginx
    depends_on:
      - gobrokersvc
    build:
      context: compose/nginx
      dockerfile: Dockerfile
