all:
	docker-compose up

clean:
	rm -rf ../compose/cachedata
	rm -rf ../compose/logs
	rm -rf ../compose/postgres/pgdata
	rm -rf ../compose/marketstore/mktsdb
	rm -rf ../compose/prjdata
	rm -rf ../compose/rmqdata
	rm -rf ../compose/marketstore/mktsdb